---
on:
  pull_request:
    branches:
      - 'main-*'
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created]

jobs:
  fast_forward_job:
    name: Fast Forward Job
    # Skip if not mergeable, or not off mainline base branch,
    # or if labeled do-not-merge
    # Force run job on /try-to-merge comment
    if: >
      ( ( github.event.pull_request.mergeable_state == 'clean' ) &&
        ( startswith( github.event.pull_request.base.ref, 'main-' ) ) &&
        ( !contains( github.event.pull_request.labels.*.name, 'do-not-merge' ) ) ) ||
      ( ( github.event.comment != '' ) && 
        ( github.event.issue.pull_request != '' ) && 
        ( contains(github.event.comment.body, '/try-to-merge' ) ) )

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}
      SOURCE_BRANCH: ${{ github.event.pull_request.head.ref }}
      PR_URL: ${{ github.event.issue.pull_request.url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: FF PR
        uses: ./
        id: ff-pr
