---
on: 
  pull_request:
    branches: [main-eos-trunk]
jobs:
  fast_forward_job:
    name: Fast Forward Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
